CREATE TABLE `item_lego` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `set_number` VARCHAR(50) DEFAULT NULL,
  `piece_count` INT UNSIGNED DEFAULT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
